export var MOCK_DATA = {
    "groups":{
      "_chl918k5t":{
         "id":"_chl918k5t",
         "name":{
            "value":"_a2c0381i8",
            "type":"ref"
         },
         "members":{
            "_bq7sckifu":{
               "id":"_bq7sckifu",
               "name":{
                  "value":"_d6ld1zi42",
                  "type":"ref"
               }
            },
            "_kwfx62pdg":{
               "id":"_kwfx62pdg",
               "name":{
                  "value":"_fffc2si49",
                  "type":"ref"
               }
            },
            "_5s35dt5je":{
               "id":"_5s35dt5je",
               "name":{
                  "value":"_xak1kspog",
                  "type":"ref"
               }
            },
            "_y89jjr00t":{
               "id":"_y89jjr00t",
               "name":{
                  "value":"_ep571i4x9",
                  "type":"ref"
               }
            },
            "_rzamc0rn85":{
               "id":"_rzamc0rn85",
               "name":{
                  "value":"_o5cb0egsq",
                  "type":"ref"
               }
            },
            "_6p2nb9dpd":{
               "id":"_6p2nb9dpd",
               "name":{
                  "value":"_s3jtx9dmz",
                  "type":"ref"
               }
            }
         },
         "expenses":{
            "_7l83m02dk":{
               "id":"_7l83m02dk",
               "amount":"500",
               "for":"pizza",
               "paidBy":[
                  {
                     "user":{
                        "id":"_bq7sckifu",
                        "name":{
                           "value":"_d6ld1zi42",
                           "type":"ref"
                        }
                     },
                     "amount":"500"
                  }
               ],
               "sharedBy":[
                  {
                     "user":{
                        "id":"_bq7sckifu",
                        "name":{
                           "value":"_d6ld1zi42",
                           "type":"ref"
                        }
                     },
                     "amount":"250"
                  },
                  {
                     "user":{
                        "id":"_kwfx62pdg",
                        "name":{
                           "value":"_fffc2si49",
                           "type":"ref"
                        }
                     },
                     "amount":"250"
                  }
               ]
            },
            "_4unwsdj84":{
               "id":"_4unwsdj84",
               "amount":"300",
               "for":"cold drinks",
               "paidBy":[
                  {
                     "user":{
                        "id":"_kwfx62pdg",
                        "name":{
                           "value":"_fffc2si49",
                           "type":"ref"
                        }
                     },
                     "amount":"300"
                  }
               ],
               "sharedBy":[
                  {
                     "user":{
                        "id":"_bq7sckifu",
                        "name":{
                           "value":"_d6ld1zi42",
                           "type":"ref"
                        }
                     },
                     "amount":"150"
                  },
                  {
                     "user":{
                        "id":"_kwfx62pdg",
                        "name":{
                           "value":"_fffc2si49",
                           "type":"ref"
                        }
                     },
                     "amount":"150"
                  }
               ]
            },
            "_yms36fofn":{
               "id":"_yms36fofn",
               "amount":"400",
               "for":"hot cacke",
               "paidBy":[
                  {
                     "user":{
                        "id":"_5s35dt5je",
                        "name":{
                           "value":"_xak1kspog",
                           "type":"ref"
                        }
                     },
                     "amount":"400"
                  }
               ],
               "sharedBy":[
                  {
                     "user":{
                        "id":"_bq7sckifu",
                        "name":{
                           "value":"_d6ld1zi42",
                           "type":"ref"
                        }
                     },
                     "amount":"200"
                  },
                  {
                     "user":{
                        "id":"_kwfx62pdg",
                        "name":{
                           "value":"_fffc2si49",
                           "type":"ref"
                        }
                     },
                     "amount":"200"
                  }
               ]
            }
         }
      },
      "_f9ojhjh91":{
         "id":"_f9ojhjh91",
         "name":{
            "value":"_ggjwdz1wj",
            "type":"ref"
         },
         "members":{
          "_bq7sckifu":{
             "id":"_bq7sckifu",
             "name":{
                "value":"_d6ld1zi42",
                "type":"ref"
             }
          },
          "_kwfx62pdg":{
             "id":"_kwfx62pdg",
             "name":{
                "value":"_fffc2si49",
                "type":"ref"
             }
          },
          "_5s35dt5je":{
             "id":"_5s35dt5je",
             "name":{
                "value":"_xak1kspog",
                "type":"ref"
             }
          },
          "_y89jjr00t":{
             "id":"_y89jjr00t",
             "name":{
                "value":"_ep571i4x9",
                "type":"ref"
             }
          },
          "_rzamc0rn85":{
             "id":"_rzamc0rn85",
             "name":{
                "value":"_o5cb0egsq",
                "type":"ref"
             }
          },
          "_6p2nb9dpd":{
             "id":"_6p2nb9dpd",
             "name":{
                "value":"_s3jtx9dmz",
                "type":"ref"
             }
          }
       },
       "expenses":{}
      },
      "_eudt1lqoh":{
         "id":"_eudt1lqoh",
         "name":{
            "value":"_234er12oq",
            "type":"ref"
         },
         "members":{
          "_bq7sckifu":{
             "id":"_bq7sckifu",
             "name":{
                "value":"_d6ld1zi42",
                "type":"ref"
             }
          },
          "_kwfx62pdg":{
             "id":"_kwfx62pdg",
             "name":{
                "value":"_fffc2si49",
                "type":"ref"
             }
          },
          "_5s35dt5je":{
             "id":"_5s35dt5je",
             "name":{
                "value":"_xak1kspog",
                "type":"ref"
             }
          },
          "_y89jjr00t":{
             "id":"_y89jjr00t",
             "name":{
                "value":"_ep571i4x9",
                "type":"ref"
             }
          },
          "_rzamc0rn85":{
             "id":"_rzamc0rn85",
             "name":{
                "value":"_o5cb0egsq",
                "type":"ref"
             }
          },
          "_6p2nb9dpd":{
             "id":"_6p2nb9dpd",
             "name":{
                "value":"_s3jtx9dmz",
                "type":"ref"
             }
          }
       },
       "expenses":{}
      },
      "_ga3mtde5e":{
         "id":"_ga3mtde5e",
         "name":{
            "value":"_l2yb5wu65",
            "type":"ref"
         },
         "members":{
          "_bq7sckifu":{
             "id":"_bq7sckifu",
             "name":{
                "value":"_d6ld1zi42",
                "type":"ref"
             }
          },
          "_kwfx62pdg":{
             "id":"_kwfx62pdg",
             "name":{
                "value":"_fffc2si49",
                "type":"ref"
             }
          },
          "_5s35dt5je":{
             "id":"_5s35dt5je",
             "name":{
                "value":"_xak1kspog",
                "type":"ref"
             }
          },
          "_y89jjr00t":{
             "id":"_y89jjr00t",
             "name":{
                "value":"_ep571i4x9",
                "type":"ref"
             }
          },
          "_rzamc0rn85":{
             "id":"_rzamc0rn85",
             "name":{
                "value":"_o5cb0egsq",
                "type":"ref"
             }
          },
          "_6p2nb9dpd":{
             "id":"_6p2nb9dpd",
             "name":{
                "value":"_s3jtx9dmz",
                "type":"ref"
             }
          }
       },
       "expenses":{}
      }
   },
   "refrences":{
      "_d6ld1zi42":"sam",
      "_fffc2si49":"dev",
      "_xak1kspog":"harry",
      "_ep571i4x9":"jhon",
      "_o5cb0egsq":"marini",
      "_s3jtx9dmz":"tonya",
      "_a2c0381i8":"dinner party @ venky's",
      "_ggjwdz1wj":"LA trip",
      "_234er12oq":"Jan shared room exppenses",
      "_l2yb5wu65":"office team lunch"
   }
};